### ISSUE TITLE
Load Entire Volume as Array

### ISSUE THREAD

**Issue by sklausing** [NorthStarImaging/efX-SDK#5]
Is there a way to load the entire volume as an array in Python? Preferably into a numpy array without having to save out each slice as a tiff image and reload each tiff image back in?

**Comment by jjtParadox** [comment]
The return value of the `read_slice` function in our [python wrapper](https://github.com/NorthStarImaging/efX-SDK/blob/main/includes/nsiefx.py) can be accessed like any other 2D python array (i.e. `value = slice[row][column]`), so you could iterate over the slices and store each slice in an array to create a 3D array of all the slices.

Additionally, numpy has its own [C-Types Foreign Function Interface](https://numpy.org/doc/stable/reference/routines.ctypeslib.html) (`numpy.ctypeslib`) that can quickly transform the return value of `read_slice` into a 2D numpy array of the slice:

```python
slice = volume.read_slice(slice_index)
npyslice = numpy.ctypeslib.as_array(slice, (volume.slice_height(),))
```

**Comment by sklausing** [comment]
Awesome thank you!
